version: '3.1'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8000:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
    links:
      - wordpress
    restart: always
  
  mysql:
    image: mysql:8
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Welcome1
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: Welcome1
    restart: always
  
  wordpress:
    image: wordpress:php7.3-fpm
    ports:
      - '9000:9000'
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=exampledb
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=Welcome1
    links:
      - mysql
    restart: always
